### ISSUE TITLE
Use with BottomNavigationBar()

### ISSUE THREAD

**Issue by idkq** [Kleak/flouter#7]
How to use the library with BottomNavigationBar()?

I tried these but not sure what the best solution is:
https://stackoverflow.com/questions/55888715/how-to-persist-bottomnavigationbar-when-using-flutter-navigation-and-routes

https://stackoverflow.com/questions/49681415/flutter-persistent-navigation-bar-with-named-routes

**Comment by kevin-sakemaer** [comment]
I didn't tested nested flouter router as of now but it's in the roadmap #5 as soon as this is well tested i will add an example and how to do it in the readme.

For now you should be able to follow what is in the link you put above but i think it will not update the URL in your browser.
